version: 0.2

env:
  variables:
    AWS_REGION: "ap-south-1"
    ECR_REPO_URI: "654485376127.dkr.ecr.ap-south-1.amazonaws.com/my-webapp"
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI
      
      # Debug (IMPORTANT 🔥)
      - echo "Current directory:"
      - pwd
      - echo "Listing files:"
      - ls -la

      # Tag logic
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:-latest}

  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Building Docker image..."

      # Explicit Dockerfile (fix)
      - docker build -t myapp -f Dockerfile .

      - docker tag myapp:latest $ECR_REPO_URI:latest
      - docker tag myapp:latest $ECR_REPO_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing images to ECR..."
      - docker push $ECR_REPO_URI:latest
      - docker push $ECR_REPO_URI:$IMAGE_TAG

      - echo "Creating imageDetail.json..."
      - printf '{"ImageURI":"%s"}' $ECR_REPO_URI:$IMAGE_TAG > imageDetail.json

artifacts:
  files:
    - imageDetail.json
    - appspec.yml
    - scripts/**/*
